"$schema" = "https://starship.rs/config-schema.json"

format = """
[](fg:color_fg_light)\
$os\
[](fg:color_fg_light bg:color_dir)\
$directory\
[ ](fg:color_dir)\
"""

# right_format = """
# $git_branch\
# $git_status\
# $docker_context\
# $container\
# $hostname\
# $package\
# $c\
# $rust\
# $golang\
# $nodejs\
# $php\
# $java\
# $kotlin\
# $haskell\
# $python\
# $cmd_duration\
# """
right_format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$container\
$shell\
"""

palette = "main"

[palettes.main]
color_fg_light = "#DBF5FA"
color_fg_dark = "#010228"
color_dir = "#0077B6"
color_git = "#689d6a"
color_docker = "#1D63ED"
color_container = "#4F433C"
color_ssh = "#73BF45"
color_rust = "#d65d0e"
color_java = "#d65d0e"
color_c = "#649AD2"
color_cmake = "#014D8B"
color_cmd_duration = "#3c3836"
color_battery = "#3c3836"
color_package = "#AD7E4E"

[os]
disabled = false
style = "bg:color_fg_light fg:color_dir"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "fg:color_fg_light bg:color_dir"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
"home_symbol" = "󰋜 "

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = " 󰝚 "
"Pictures" = "  "
"Developer" = " 󰲋 "

[git_branch]
symbol = ""
style = "fg:color_fg_dark bg:color_git"
format = "[](fg:color_git)[$symbol( $branch) ]($style)"

[git_status]
disabled = false
style = "fg:color_fg_dark bg:color_git"
format = "[($all_status$ahead_behind)]($style)[](fg:color_git)"

[docker_context]
symbol = ""
style = "fg:color_fg_light bg:color_docker"
format = "[](fg:color_docker)[$symbol( $context)]($style)[](fg:color_docker)"

[container]
symbol = "󰆦"
style = "fg:color_fg_light bg:color_container"
format = "[](fg:color_container)[$symbol( $name)]($style)[](fg:color_container)"

[username]
disabled = true

[hostname]
ssh_only = true
ssh_symbol = "󰖩"
style = "fg:color_fg_dark bg:color_ssh"
format = "[](fg:color_ssh)[$ssh_symbol]($style)[](fg:color_ssh)"

[package]
symbol = "󰏖"
style = "fg:color_fg_dark bg:color_package"
format = "[](fg:color_package)[$symbol( $version)]($style)[](fg:color_package)"

[nodejs]
symbol = ""
style = "bg:color_dir"
format = "[[$symbol( $version)](fg:color_fg_light bg:color_dir)]($style)"

[c]
symbol = ""
style = "bg:color_c"
format = "[](fg:color_c)[$symbol( $version)]($style)[](fg:color_c)"

[cmake]
disabled = false
symbol = "󰔶"
style = "fg:color_fg_light bg:color_cmake"
format = "[](fg:color_cmake)[$symbol( $version)]($style)[](fg:color_cmake)"

[rust]
symbol = ""
style = "fg:color_fg_dark bg:color_rust"
format = "[](fg:color_rust)[$symbol( $version)]($style)[](fg:color_rust)"

[golang]
symbol = ""
style = "bg:color_dir"
format = "[[ $symbol( $version) ](fg:color_fg_light bg:color_dir)]($style)"

[php]
symbol = ""
style = "bg:color_dir"
format = "[[ $symbol( $version) ](fg:color_fg_light bg:color_dir)]($style)"

[java]
symbol = ""
style = "fg:color_fg_dark bg:color_java"
format = "[](fg:color_java)[$symbol( $version)]($style)[](fg:color_java)"

[kotlin]
symbol = ""
style = "bg:color_dir"
format = "[[ $symbol( $version) ](fg:color_fg_light bg:color_dir)]($style)"

[haskell]
symbol = ""
style = "bg:color_dir"
format = "[[ $symbol( $version) ](fg:color_fg_light bg:color_dir)]($style)"

[python]
symbol = ""
style = "bg:color_dir"
format = "[[ $symbol( $version) ](fg:color_fg_light bg:color_dir)]($style)"

[time]
disabled = false
time_format = "%R"
format = "[ $time ](color_fg_light)"

[line_break]
disabled = true

[character]
disabled = false
success_symbol = "[❯](bold fg:color_dir)"

[cmd_duration]
disabled = false
min_time = 100
style = "bold fg:color_fg_light bg:color_cmd_duration"
format = "[](fg:color_cmd_duration)[$duration]($style)[](fg:color_cmd_duration)"

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁽 "
empty_symbol = "󰂎 "
format = "[](fg:color_battery)[$symbol$percentage](bg:color_battery)[](fg:color_battery)"
disabled = false

[[battery.display]]
threshold = 20
style = "red bold"
