"$schema" = "https://starship.rs/config-schema.json"

format = "[]()$os[](bg:bright-blue)$directory[ ](fg:bright-blue)"

right_format = """
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
\
$package\
\
$c\
$cmake\
$cobol\
$crystal\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
\
$aws\
$buf\
$conda\
$container\
$docker_context\
$gcloud\
$hostname\
$nix_shell\
$meson\
$openstack\
$spack\
$singularity\
$kubernetes\
\
$battery\
$cmd_duration\
\
$jobs\
$username\
$localip\
$shlvl\
$memory_usage\
$azure\
$env_var\
$custom\
$direnv\
$shell\
$sudo\
$status\
"""

[os]
disabled = false
format = "[$symbol ](inverted)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
format = "[ ($read_only )$path ](inverted fg:bright-blue)"
read_only = "󰌾"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
"home_symbol" = "󰋜 "

[directory.substitutions]
"/Documents/" = "/ 󰈙 /"
"/Downloads/" = "/  /"
"/Music/" = "/ 󰝚 /"
"/Pictures/" = "/  /"
"/Developer/" = "/  /"
"/Programming/" = "/  /"
"/Games/" = "/ 󰊗 /"
"/Videos/" = "/ 󰕧 /"
"/Experiments/" = "/  /"
"/School/" = "/ 󰑴 /"
"/Projects/" = "/  /"

[git_branch]
disabled = false
only_attached = false
always_show_remote = false
ignore_branches = []
symbol = ""
style = "fg:green"
format = "[]($style)[$symbol $branch(:$remote_branch) ]($style inverted)"

[git_commit]
style = "fg:green"
format = "[\\($hash$tag\\) ]($style inverted)"

[git_state]
style = "fg:green"
format = "[\\($state( $progress_current/$progress_total)\\) ]($style inverted)"

[git_metrics]
disabled = true

[git_status]
disabled = false
style = "fg:green"
format = "[($all_status$ahead_behind)]($style inverted)[]($style)"

[docker_context]
symbol = ""
style = "fg:bright-purple"
format = "[]($style)[$symbol( $context)]($style inverted)[]($style)"

[container]
symbol = "󰆦"
style = "fg:bright-purple"
format = "[]($style)[$symbol( $name)]($style inverted)[]($style)"

[username]
disabled = true

[hostname]
ssh_only = true
ssh_symbol = "󰖩"
style = "fg:green"
format = "[]($style)[$ssh_symbol]($style inverted)[]($style)"

[package]
symbol = "󰏖"
style = "fg:bright-yellow"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[nodejs]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[c]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[cmake]
disabled = false
symbol = "󰔶"
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[rust]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[golang]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[php]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[java]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[kotlin]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[haskell]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[python]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[gradle]
symbol = ""
style = "fg:cyan"
format = "[]($style)[$symbol( $version)]($style inverted)[]($style)"

[time]
disabled = false
time_format = "%R"
format = "[ $time ](blue)"

[line_break]
disabled = true

[character]
disabled = false
success_symbol = "[❯](bold fg:blue)"

[cmd_duration]
disabled = false
min_time = 100
style = "fg:bright-blue"
format = "[]($style)[$duration]($style inverted)[]($style)"

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰁽 "
empty_symbol = "󰂎 "
format = "[]($style)[$symbol$percentage]($style inverted)[]($style)"
disabled = false

[[battery.display]]
threshold = 20
style = "fg:bright-red"
